# Generated by Django 3.2.5 on 2021-10-11 03:54

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('review', models.CharField(blank=True, max_length=100, null=True)),
                ('evaluation', models.CharField(choices=[('excellent', '☆'), ('good', '◎'), ('normal', '〇'), ('bad', '×')], default='good', max_length=10)),
                ('place', models.CharField(choices=[('home', '家'), ('zym', 'ジム(御殿下)'), ('others', 'その他')], default='home', max_length=10, verbose_name='Place')),
                ('created_at', models.DateField(default=datetime.datetime(2021, 10, 11, 3, 54, 47, 943179, tzinfo=utc), verbose_name='Date')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_type', models.CharField(choices=[('push-up_normal', '腕立て(normal)'), ('push-up_wide', '腕立て(wide)'), ('bench_press', 'ベンチプレス'), ('shoulder_press', 'ショルダーバックプレス'), ('arm_curl', 'アームカール'), ('kick_back', 'キックバック'), ('something_new', '新種目')], max_length=40)),
                ('weight', models.IntegerField(default=12, verbose_name='Weight[Kg]')),
                ('set1', models.IntegerField(default=10)),
                ('set2', models.IntegerField(blank=True, default=9, null=True)),
                ('set3', models.IntegerField(blank=True, default=8, null=True)),
                ('created_at', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.training')),
            ],
        ),
    ]
