# Generated by Django 3.2.5 on 2021-10-11 03:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 11, 3, 56, 19, 102318, tzinfo=utc), verbose_name='Date'),
        ),
    ]
