# Generated by Django 3.2.5 on 2021-10-11 12:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_alter_training_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='title',
        ),
        migrations.AlterField(
            model_name='content',
            name='training_type',
            field=models.CharField(choices=[('push-up_normal', '腕立て(normal)'), ('push-up_wide', '腕立て(wide)'), ('bench_press', 'ベンチプレス'), ('arm_variations', '上腕総合（家）'), ('shoulder_press', 'ショルダーバックプレス'), ('side_rise', 'サイドレイズ'), ('arm_curl', 'アームカール'), ('kick_back', 'キックバック'), ('something_new', '新種目')], max_length=40),
        ),
        migrations.AlterField(
            model_name='training',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 11, 12, 56, 29, 159217, tzinfo=utc), verbose_name='Date'),
        ),
    ]
