# Generated by Django 3.2.5 on 2021-10-11 13:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_auto_20211011_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='body_weight_10',
            field=models.PositiveIntegerField(default=700),
        ),
        migrations.AlterField(
            model_name='content',
            name='set1',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='content',
            name='set2',
            field=models.PositiveIntegerField(blank=True, default=9, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='set3',
            field=models.PositiveIntegerField(blank=True, default=8, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='weight',
            field=models.PositiveIntegerField(default=12, verbose_name='Weight[Kg]'),
        ),
        migrations.AlterField(
            model_name='training',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 11, 13, 28, 46, 10567, tzinfo=utc), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='training',
            name='place',
            field=models.CharField(choices=[('home', 'Home'), ('zym', 'Zym'), ('others', 'Others')], default='home', max_length=10, verbose_name='Place'),
        ),
    ]
